require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'TripPlanner' do
  $ReactNativeMapboxGLIOSVersion = '~> 6.1'
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  target 'TripPlannerTests' do
    inherit! :complete
    # Pods for testing
  end
  
  pre_install do |installer|
    $RNMBNAV.pre_install(installer)
    $RNMBGL.pre_install(installer)
    # any other pre install hooks here
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  
  post_install do |installer|
    $RNMBNAV.post_install(installer)
    $RNMBGL.post_install(installer)
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
